In [1]:
import pandas as pd

In [19]:
data={
   "Bedrooms":[3,2,1],
    "Area_sqft":[2000,850,2500],
    "Location":['Downtown','Suburb','Downtown'],
    "Price":[550000,180000,680000]}

In [14]:
d=pd.DataFrame(data)

In [15]:
d

   Bedrooms  Area_sqft  Location   Price  index
0         3       2000  Downtown  550000      1
1         2        850    Suburb  180000      2
2         1       2500  Downtown  680000      3

In [16]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Bedrooms   3 non-null      int64
 1   Area_sqft  3 non-null      int64
 2   Location   3 non-null      object
 3   Price      3 non-null      int64
 4   index      3 non-null      int64
dtypes: int64(4), object(1)
memory usage: 252.0+ bytes

In [20]:
d.isnull()

   Bedrooms  Area_sqft  Location  Price  index
0     False      False     False  False  False
1     False      False     False  False  False
2     False      False     False  False  False

In [ ]:
d.